name: flutter_rakuraku_home
description: らくらくフォン用のランチャーアプリ

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  android_intent_plus: ^3.1.5
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  receive_intent: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
